# When master is 'manually' updated, regenerate the site via
# travis.
#
# When master is updated via the update function, it should take
# care of updating both the source and target repo's instead of
# this script, but currently we don't defend against this yet.

script:
  - openssl aes-256-cbc -K $encrypted_0c8de898dd1a_key -iv $encrypted_0c8de898dd1a_iv -in id_rsa.enc -out id_rsa -d
  - chmod 0600 id_rsa
  - export GIT_SSH_COMMAND='ssh -i id_rsa'
  - git clone git@github.com:raboof/serverless-wiki code
  - git clone -b gh-pages git@github.com:raboof/testwiki target
  - export SOURCE=.
  - export TARGET=target
  - code/generate.sh
  - cd target; git status; git diff

branches:
  only:
  - master
