# When master is 'manually' updated, regenerate the site via
# travis.
#
# When master is updated via the update function, it should take
# care of updating both the source and target repo's instead of
# this script - but currently we don't defend against this yet.

install:
  - pip install --user boto3

script:
  - # openssl aes-256-cbc -K $encrypted_0c8de898dd1a_key -iv $encrypted_0c8de898dd1a_iv -in id_rsa.enc -out id_rsa -d
  - # chmod 0600 id_rsa
  - # export GIT_SSH_COMMAND='ssh -i '`pwd`'/id_rsa'
  - git clone https://github.com/raboof/serverless-wiki code
  - mkdir target
  - export SOURCE=.
  - export TARGET=target
  - code/generate.sh
  - ls -alFhR target

deploy:
  provider: script
  script: code/deploy.py
#  script: git add .; git status; git commit -m "Manual update on master"; git push
  skip_cleanup: true

env:
  global:
    - AWS_ACCESS_KEY_ID="AKIAIDSMELSBUXLZJY2Q"
    - AWS_DEFAULT_REGION="eu-west-1"
    - secure: "shGGAY0Sft/ZiTWs3eu8aClW0CPBv0VfxBllJIg6l1Kf/SBxJnPqN4uJgiY3vlnZ/18mP4ydsl78qS0rGlaZkw8NH2zoMVrU0wflVKREuzelrWIJVKGTN9UqsRWE65ej5KqjPZOS+GyMNa5M+OFU250fzba+Dx1rDAfKohUaEThZ+oIJ52XqvhFdZj0b/62SNuHANE4yJm3VdYvNW5/W4YxBE6KJqu3trt5q6u97AkGyRTgDnBJQnNVU8AeBX4D6NBGOxJJE64NK8xNJevW7AEMEf6vr2gWumhkCyliZ0AbkNcc28xZxvISkNGIpJ0WvlfBmRBKRNjXzXWb3snLbHO6M2yB4gLkDCr9UGoGyt75LPjWyf8pN6m4+eGkrRDzaJZGfQB9A6Zj3FtoRZZw4OtlpSB98HnjGYpEtI96+AORZL0ndjZJcoH9ZsWApiC6d795tIK3cQt9KE5JAv12glW/iakwZ/UxvsWRFHAlxvXyQBXseEkj0e9bjyBVGZ7inRVyGcCv6AMJ6rxG/VwU/erEMsPloIIfgp46ie2SY8mbLY9xlLb7wXZg6VcaXjPAjEqTsXvgStij3TjK89NKDJ7dAoy2ncNFQtUCJwqAUw/KLuL1dgkylL2VMNqhbNcKnq5JB4OIQ/50eDf2joRAaGNw5sKnVzPTZ3lwppC+dkAY="
